### PR TITLE
Added support for floating point field i.e. Fields.number

### PR DESCRIPTION
**Pull request by anbhole**
Hi I have added a new field 'number' in Fields. I needed this to enter latitude and longitude. Please check.

### CODE REVIEW

**Comment by paveltiunov** [comment]
@anbhole does it fix #100 ?

**Comment by anbhole** [comment]
Yes it does with my latest commit.

**Comment by paveltiunov** [comment]
Cool! Thanks!

**Comment by nick13jaremek** [comment]
Was there a new `allcountjs` version released with this added Field type? It would be greatly appreciated as we are precisely requiring it for latitude/longitude data.

**Comment by paveltiunov** [comment]
@nick13jaremek will release 1.24.1

**Pull request merged**
