### PR TITLE
Added code for filtering with $or and $and

### PR DESCRIPTION
**Pull request by m-byte**
Since I needed to do some slightly more complex filtering, I modified storage-driver.js to support this. It is now recursively scanning through the filtering object.

### CODE REVIEW

**Comment by paveltiunov** [comment]
Incredible work! Thanks for that! This is really complex stuff. 

@m-byte do you think you can add some tests for it?

**Comment by m-byte** [comment]
@paveltiunov sure, shouldn't be a problem.

One question though:
Should the user rather enter filters in Mongodb syntax (`$or: {}`) or Strongloop syntax (`or: {}`)? Right now, it is `$or: {}`. It would be easy to change, though.

**Comment by m-byte** [comment]
@paveltiunov which file do the tests belong into? A new `storage-driver-test.js` or one of the existing ones?

**Comment by paveltiunov** [comment]
@m-byte I think we can support both 😄 I think you can add it to `storage-driver-test.js`.

**Pull request merged**
